name: "build-release"

on:
  push:
    paths: 
      - '**.py'
      - '**.yml'
    branches:
      - "master"

jobs:
  build-release:
    name: "Build & Release"
    runs-on: "windows-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install Python 3"
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: "Install dependencies"
        run: |
          python -m pip install pyinstaller

      - name: "Build application"
        run: |
          pyinstaller --onefile .\music_gui_volume.py

      - name: "Automatic Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest release"
          files: |
            ./dist/music_gui_volume.exe
